import React from "react";
import Link from "@docusaurus/Link";
import useBaseUrl from "@docusaurus/useBaseUrl";
import Layout from "@theme/Layout";
import {
  ArrowLeftRight,
  ArrowRight,
  BadgeCheck,
  Bot,
  Clock,
  Code2,
  Database,
  FileCheck,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  GitBranch,
  Globe,
  LayoutDashboard,
  Lock,
  Monitor,
  Package,
  PenLine,
  Printer,
  Search,
  Server,
  ShieldCheck,
  Stamp,
  Users,
} from "lucide-react";
import { renderSeal, type TrustTier } from "@dotit/core";
import styles from "./index.module.css";

/* ── Live Hash-Based Ambient Seals ──────────────────────────────────────────
 * Four real seals, one per trust tier, rendered at build/render time by
 * @dotit/core's renderSeal (pure SVG string, no DOM) from a sample SHA-256.
 * These are the genuine article — same code the editor, desktop badge and
 * verify portal use — and weigh ~2KB each vs the 1.5MB concept PNGs.
 */
const LIVE_SEALS: { tier: TrustTier; hash: string; caption: string }[] = [
  {
    tier: "draft",
    hash: "sha256:3b1c9d7e4f2a8056c1d4e9b2a7f60318d5e2c4b9a1786f30e9d2c5b48a17f602",
    caption: "Draft",
  },
  {
    tier: "signed",
    hash: "sha256:8f2a4c0e9b71d6538a2e7c1f04b93d68e5a1c7920f63b48d1e9c20a5743f81b6",
    caption: "Signed",
  },
  {
    tier: "certified",
    hash: "sha256:c4e91a37b08d2f561c9a4e7032b85d19f6e2a8c50d1937b46e8a2c105f73d984",
    caption: "Certified",
  },
  {
    tier: "root-certified",
    hash: "sha256:a17f60318d5e2c4b9c9d7e4f2a8056c13b1a7860f30e9d2c5b481f602a7f9c204",
    caption: "Root-certified ★",
  },
];

// A TEMPLATE sits OUTSIDE the four trust tiers — a blueprint, not a record. Its
// seal is the distinct slate, dashed ring (no hash crown) that @dotit/core
// renders for tier "template". Kept separate from the trust seals on purpose.
const TEMPLATE_SEAL: { tier: TrustTier; hash: string; caption: string } = {
  tier: "template",
  hash: "sha256:00000000",
  caption: "Template",
};

function LiveSealRow(): React.ReactElement {
  return (
    <figure className={styles.sealFig}>
      <div className={styles.liveSealRow}>
        {LIVE_SEALS.map((s) => (
          <div className={styles.liveSeal} key={s.tier}>
            <span
              className={styles.liveSealArt}
              // Pure SVG string from @dotit/core — deterministic in the hash.
              dangerouslySetInnerHTML={{
                __html: renderSeal({ hash: s.hash, tier: s.tier, size: 104 }),
              }}
            />
            <span className={styles.liveSealCaption}>{s.caption}</span>
          </div>
        ))}
        {/* The template seal — grouped here but visually fenced off from the
            four trust tiers, because a template is OUTSIDE them. */}
        <div className={styles.liveSealDivider} aria-hidden />
        <div
          className={`${styles.liveSeal} ${styles.liveSealTemplate}`}
          key={TEMPLATE_SEAL.tier}
        >
          <span
            className={styles.liveSealArt}
            dangerouslySetInnerHTML={{
              __html: renderSeal({
                hash: TEMPLATE_SEAL.hash,
                tier: TEMPLATE_SEAL.tier,
                size: 104,
              }),
            }}
          />
          <span className={styles.liveSealCaption}>{TEMPLATE_SEAL.caption}</span>
        </div>
      </div>
      <figcaption className={styles.shotCaption}>
        Live, not mock-ups — each generated by <code>@dotit/core</code> from the
        document&apos;s SHA-256 hash. Same doc → same seal; any change → a
        different one. Colour states the tier: gray draft, blue signed, green
        certified, gold root-certified. The slate dashed seal is a{" "}
        <strong>template</strong> — a blueprint, not a record: it sits{" "}
        <em>outside</em> the trust tiers (merge it with data to produce a
        signable document).
      </figcaption>
    </figure>
  );
}

/* ── Static .it source rendering (no runtime parsing — just display) ── */

const TRUST_KEYWORDS = new Set([
  "sign",
  "approve",
  "freeze",
  "track",
  "amendment",
  "history",
  "revision",
  "توقيع",
  "اعتماد",
  "تجميد",
  "تتبع",
  "تعديل",
]);

function Tok({ text }: { text: string }) {
  const parts = text.split(/(\{\{[^}]*\}\})/g);
  return (
    <>
      {parts.map((p, i) =>
        p.startsWith("{{") ? (
          <span key={i} className={styles.srcToken}>
            {p}
          </span>
        ) : (
          <React.Fragment key={i}>{p}</React.Fragment>
        ),
      )}
    </>
  );
}

function ItLine({ line }: { line: string }) {
  if (!line.trim()) return <div className={styles.srcLine}>&nbsp;</div>;
  if (line.trimStart().startsWith("//")) {
    return (
      <div className={`${styles.srcLine} ${styles.srcComment}`}>{line}</div>
    );
  }
  if (/^\s*\|/.test(line.trimStart())) {
    const parts = line.split("|");
    return (
      <div className={styles.srcLine}>
        {parts.map((p, i) => (
          <React.Fragment key={i}>
            {i > 0 && <span className={styles.srcPipe}>|</span>}
            <Tok text={p} />
          </React.Fragment>
        ))}
      </div>
    );
  }
  const m = line.match(/^([\p{L}][\p{L}\p{N}_-]*):(.*)$/u);
  if (!m) return <div className={styles.srcLine}>{line}</div>;
  const kw = m[1];
  const rest = m[2];
  const kwClass = TRUST_KEYWORDS.has(kw) ? styles.srcTrustKw : styles.srcKw;
  const segments = rest.split(" | ");
  return (
    <div className={styles.srcLine}>
      <span className={kwClass}>{kw}:</span>
      {segments.map((seg, i) => {
        const pm = i > 0 ? seg.match(/^(\s*[\p{L}][\p{L}\p{N}_-]*):\s?(.*)$/u) : null;
        return (
          <React.Fragment key={i}>
            {i > 0 && <span className={styles.srcPipe}>{" | "}</span>}
            {pm ? (
              <>
                <span className={styles.srcProp}>{pm[1]}:</span>{" "}
                <Tok text={pm[2]} />
              </>
            ) : (
              <Tok text={seg} />
            )}
          </React.Fragment>
        );
      })}
    </div>
  );
}

function ItSource({
  title,
  code,
  rtl,
}: {
  title: string;
  code: string;
  rtl?: boolean;
}) {
  return (
    <div className={styles.srcPane}>
      <div className={styles.paneHeader}>
        <span className={styles.paneDots}>
          <i />
          <i />
          <i />
        </span>
        {title}
      </div>
      <pre className={styles.srcBody} dir={rtl ? "rtl" : "ltr"}>
        {code.split("\n").map((l, i) => (
          <ItLine key={i} line={l} />
        ))}
      </pre>
    </div>
  );
}

function DarkCode({ title, code }: { title: string; code: string }) {
  return (
    <div className={styles.srcPane}>
      <div className={styles.paneHeader}>
        <span className={styles.paneDots}>
          <i />
          <i />
          <i />
        </span>
        {title}
      </div>
      <pre className={styles.srcBody}>{code}</pre>
    </div>
  );
}

type TermLine = {
  t: "cmd" | "ok" | "err" | "out" | "comment" | "blank";
  s?: string;
};

function TerminalPane({ title, lines }: { title: string; lines: TermLine[] }) {
  const cls: Record<string, string> = {
    cmd: styles.termCmd,
    ok: styles.termOk,
    err: styles.termErr,
    out: styles.termOut,
    comment: styles.termComment,
    blank: styles.termBlank,
  };
  return (
    <div className={styles.terminal}>
      <div className={styles.paneHeader}>
        <span className={styles.paneDots}>
          <i />
          <i />
          <i />
        </span>
        {title}
      </div>
      <pre className={styles.termBody}>
        {lines.map((l, i) => (
          <div key={i} className={cls[l.t]}>
            {l.t === "blank" ? " " : l.s}
          </div>
        ))}
      </pre>
    </div>
  );
}

/* ── Example sources (static text, hand-rendered next to them) ──────── */

const INVOICE_SRC = `page: | size: A4 | margin: 20mm
header: Horizon Consulting
footer: INV-2026-042 · Page {{page}} of {{pages}}

title: Invoice INV-2026-042 | end: 2026-06-01
summary: Horizon Consulting → Acme Corp
meta: | theme: corporate | status: Unpaid

section: Bill To
contact: Acme Corp | email: accounts@acme.com | vat: VAT-300214

section: Line Items
| Description | Qty | Unit | Total |
| Consulting — May 2026 | 40 | 150.00 | 6,000.00 |
| Systems integration | 12 | 175.00 | 2,100.00 |

metric: Subtotal | value: 8,100.00 USD
metric: Tax (5%) | value: 405.00 USD
metric: Total Due | value: [8,505.00 USD]{ weight: bold }

deadline: Payment due | date: 2026-06-30 | consequence: 2% monthly late fee
sign: Layla Hassan | role: Finance Director | at: 2026-06-01T09:30:00Z
freeze: | status: locked`;

const ARABIC_SRC = `عنوان: عقد خدمات استشارية
ملخص: بين شركة الأفق للاستشارات ومؤسسة النور التجارية
بيانات: | التاريخ: 2026-06-01 | الحالة: ساري

قسم: الأطراف
جهة: شركة الأفق للاستشارات | البريد: info@alufuq.qa | السجل: CR-10442
جهة: مؤسسة النور التجارية | البريد: contact@alnoor.qa | السجل: CR-22871

قسم: نطاق العمل
نص: يقدّم الطرف الأول خدمات استشارية إدارية خلال الربع الثالث من عام 2026.
مؤشر: قيمة العقد | value: 45,000 ر.ق
مهلة: سداد الدفعة الأولى | date: 2026-07-15 | consequence: غرامة تأخير 2%

قسم: الجدول الزمني
أعمدة: المرحلة | التسليم | الموعد
صف: الأولى | دراسة الوضع الراهن | 2026-07-01
صف: الثانية | التقرير النهائي | 2026-09-30

اعتماد: روجع من الإدارة القانونية | by: سارة المنصوري | role: مستشارة قانونية
توقيع: أحمد الجابر | role: المدير التنفيذي | at: 2026-06-01T10:00:00Z
تجميد: | status: locked`;

const PRINT_SRC = `page: | size: A4 | margin: 20mm
header: ACME Holdings — Confidential
footer: Page {{page}} of {{pages}}
watermark: DRAFT | opacity: 0.1

style: text | leading: 1.6 | space-after: 12px
style: section | color: #1e3a5f | weight: 600`;

const PDF_SRC = `import { issuePDF } from "@dotit/pdf";

const { source, hash, pdf } = await issuePDF(template, data, {
  signer: "Layla Hassan",
  role: "Finance Director",
  theme: "corporate",
});
// source — the sealed .it: the queryable, verifiable record
// pdf    — real PDF bytes, ready to email or archive`;

const MCP_SRC = `{
  "mcpServers": {
    "intenttext": {
      "command": "npx",
      "args": ["-y", "-p", "@dotit/mcp", "intenttext-mcp"]
    }
  }
}`;

const MCP_TOOLS = [
  "parse_intent_text",
  "render_html",
  "render_print",
  "merge_template",
  "validate_document",
  "query_document",
  "diff_documents",
  "document_to_source",
  "extract_workflow",
  "seal_document",
  "verify_document",
  "compute_hash",
  "get_document_history",
  "sign_document",
  "verify_signatures",
  "verify_certification",
  "generate_signing_key",
];

const TRUST_TERM: TermLine[] = [
  { t: "comment", s: "// 1 · INTEGRITY — freeze the content with a SHA-256 seal" },
  { t: "cmd", s: 'dotit seal contract.it --signer "Ahmed Al-Jaber" --role "CEO"' },
  { t: "ok", s: "✅  Sealed   sha256:9f1c2ab87d…   frozen 2026-06-12T10:02Z" },
  { t: "blank" },
  { t: "comment", s: "// 2 · IDENTITY — add a real Ed25519 signature (proves WHO)" },
  { t: "cmd", s: "dotit sign contract.it --key ahmed.key" },
  { t: "ok", s: "✅  Signed   key ed25519:6f2a…   sig 30c4…" },
  { t: "blank" },
  { t: "comment", s: "// 3 · AUTHORITY — bind a KYC-verified entity via UTS certify" },
  { t: "cmd", s: "dotit verify contract.it --root uts-root.pub" },
  { t: "ok", s: "✅  Intact · signature valid · certified — offline" },
  { t: "out", s: "    Signer:    Ahmed Al-Jaber (CEO)" },
  { t: "out", s: "    Certified: Horizon Consulting · UTS-verified entity" },
  { t: "out", s: "    Chain:     root → issuing key → document  ✅" },
  { t: "blank" },
  { t: "comment", s: "// a payment term is edited after sealing…" },
  { t: "cmd", s: "dotit verify contract.it" },
  { t: "err", s: "❌  Modified since sealing" },
  { t: "out", s: "    Expected: sha256:9f1c2ab87d…" },
  { t: "out", s: "    Current:  sha256:3e8d41c09a…" },
];

const CONVERT_TERM: TermLine[] = [
  { t: "comment", s: "// bring existing files in — Markdown, HTML, Excel, Word" },
  { t: "cmd", s: "dotit convert budget.xlsx budget.it" },
  { t: "ok", s: "✅  budget.it — 3 sheets → typed tables" },
  { t: "cmd", s: "dotit convert proposal.docx proposal.it" },
  { t: "ok", s: "✅  proposal.it — headings, lists, tables preserved" },
  { t: "blank" },
  { t: "comment", s: "// and send them back out — round-trips both ways" },
  { t: "cmd", s: "dotit convert report.it report.xlsx" },
  { t: "cmd", s: "dotit convert report.it report.docx" },
  { t: "ok", s: "✅  report.xlsx · report.docx" },
];

const QUERY_TERM: TermLine[] = [
  { t: "cmd", s: "dotit query ./contracts --type deadline" },
  { t: "blank" },
  { t: "out", s: "FILE            TYPE      CONTENT             PROPERTIES" },
  { t: "out", s: "--------------  --------  ------------------  --------------------------" },
  { t: "out", s: "acme-2026.it    deadline  Payment due         date: 2026-06-30 | consequence: 2% monthly late fee" },
  { t: "out", s: "alnoor-svc.it   deadline  سداد الدفعة الأولى   date: 2026-07-15 | consequence: غرامة تأخير 2%" },
  { t: "out", s: "orbit-nda.it    deadline  Renewal notice      date: 2026-09-01" },
  { t: "blank" },
  { t: "comment", s: "// build per-folder indexes once — queries self-heal them afterwards" },
  { t: "cmd", s: "dotit index ./contracts --recursive" },
  { t: "blank" },
  { t: "comment", s: "// or ask in natural language" },
  { t: "cmd", s: 'dotit ask ./contracts "which contracts renew this quarter?"' },
];

/* ── Rendered document panes (static, hand-rendered) ─────────────────── */

function InvoicePaper() {
  return (
    <div className={styles.paper}>
      <div className={styles.paperZone}>Horizon Consulting</div>
      <div className={styles.paperBody}>
        <div className={styles.twoSided}>
          <h3 className={styles.docTitle}>Invoice INV-2026-042</h3>
          <span className={styles.docTitleEnd}>2026-06-01</span>
        </div>
        <p className={styles.docSummary}>Horizon Consulting → Acme Corp</p>
        <div className={styles.metaChips}>
          <span className={styles.metaChip}>theme: corporate</span>
          <span className={styles.metaChip}>status: Unpaid</span>
        </div>
        <div className={styles.docSection}>Bill To</div>
        <div className={styles.contactCard}>
          <Users size={15} />
          <div>
            <strong>Acme Corp</strong>
            <div className={styles.contactMeta}>
              accounts@acme.com · VAT-300214
            </div>
          </div>
        </div>
        <div className={styles.docSection}>Line Items</div>
        <table className={styles.docTable}>
          <thead>
            <tr>
              <th>Description</th>
              <th className={styles.numCell}>Qty</th>
              <th className={styles.numCell}>Unit</th>
              <th className={styles.numCell}>Total</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Consulting — May 2026</td>
              <td className={styles.numCell}>40</td>
              <td className={styles.numCell}>150.00</td>
              <td className={styles.numCell}>6,000.00</td>
            </tr>
            <tr>
              <td>Systems integration</td>
              <td className={styles.numCell}>12</td>
              <td className={styles.numCell}>175.00</td>
              <td className={styles.numCell}>2,100.00</td>
            </tr>
          </tbody>
        </table>
        <div className={styles.totalRow}>
          <span>Subtotal</span>
          <strong>8,100.00 USD</strong>
        </div>
        <div className={styles.totalRow}>
          <span>Tax (5%)</span>
          <strong>405.00 USD</strong>
        </div>
        <div className={`${styles.totalRow} ${styles.totalRowGrand}`}>
          <span>Total Due</span>
          <strong>8,505.00 USD</strong>
        </div>
        <div className={styles.deadlineBox}>
          <Clock size={14} />
          <span>
            <strong>Payment due</strong> — 2026-06-30 · 2% monthly late fee
          </span>
        </div>
        <div className={styles.trustChips}>
          <span className={`${styles.trustChip} ${styles.trustSign}`}>
            <PenLine size={14} /> Signed — Layla Hassan, Finance Director
          </span>
          <span className={`${styles.trustChip} ${styles.trustSeal}`}>
            <Lock size={14} /> Sealed · sha256:9f1c2ab87d…
          </span>
        </div>
      </div>
      <div className={styles.paperZone}>INV-2026-042 · Page 1 of 1</div>
    </div>
  );
}

function ArabicPaper() {
  return (
    <div className={styles.paper} dir="rtl" lang="ar">
      <div className={styles.paperBody}>
        <h3 className={styles.docTitle}>عقد خدمات استشارية</h3>
        <p className={styles.docSummary}>
          بين شركة الأفق للاستشارات ومؤسسة النور التجارية
        </p>
        <div className={styles.metaChips}>
          <span className={styles.metaChip}>
            التاريخ: <span dir="ltr">2026-06-01</span>
          </span>
          <span className={styles.metaChip}>الحالة: ساري</span>
        </div>
        <div className={styles.docSection}>الأطراف</div>
        <div className={styles.contactCard}>
          <Users size={15} />
          <div>
            <strong>شركة الأفق للاستشارات</strong>
            <div className={styles.contactMeta}>
              <span dir="ltr">info@alufuq.qa</span> · السجل CR-10442
            </div>
          </div>
        </div>
        <div className={styles.contactCard}>
          <Users size={15} />
          <div>
            <strong>مؤسسة النور التجارية</strong>
            <div className={styles.contactMeta}>
              <span dir="ltr">contact@alnoor.qa</span> · السجل CR-22871
            </div>
          </div>
        </div>
        <div className={styles.docSection}>نطاق العمل</div>
        <p className={styles.docText}>
          يقدّم الطرف الأول خدمات استشارية إدارية خلال الربع الثالث من عام 2026.
        </p>
        <div className={`${styles.totalRow} ${styles.totalRowGrand}`}>
          <span>قيمة العقد</span>
          <strong>45,000 ر.ق</strong>
        </div>
        <div className={styles.deadlineBox}>
          <Clock size={14} />
          <span>
            <strong>سداد الدفعة الأولى</strong> —{" "}
            <span dir="ltr">2026-07-15</span> · غرامة تأخير 2%
          </span>
        </div>
        <div className={styles.docSection}>الجدول الزمني</div>
        <table className={styles.docTable}>
          <thead>
            <tr>
              <th>المرحلة</th>
              <th>التسليم</th>
              <th>الموعد</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>الأولى</td>
              <td>دراسة الوضع الراهن</td>
              <td dir="ltr">2026-07-01</td>
            </tr>
            <tr>
              <td>الثانية</td>
              <td>التقرير النهائي</td>
              <td dir="ltr">2026-09-30</td>
            </tr>
          </tbody>
        </table>
        <div className={styles.trustChips}>
          <span className={`${styles.trustChip} ${styles.trustApprove}`}>
            <ShieldCheck size={14} /> اعتماد — سارة المنصوري، مستشارة قانونية
          </span>
          <span className={`${styles.trustChip} ${styles.trustSign}`}>
            <PenLine size={14} /> توقيع — أحمد الجابر، المدير التنفيذي
          </span>
          <span className={`${styles.trustChip} ${styles.trustSeal}`}>
            <Lock size={14} /> الوثيقة مختومة
          </span>
        </div>
      </div>
    </div>
  );
}

/* ── Hero invoice — a live, sealed .it rendered to the page (the stamp certifies
 *    it; no inline sign/seal rows — the seal STAMP is enough). ───────────────── */

const HERO_SEAL_HASH =
  "sha256:19fba2465dc18e7a3b0c4f59d2e81a6c7740bb913fce25a08d6f1b23ce40a9d7";

function HeroInvoice(): React.ReactElement {
  const stamp = renderSeal({
    hash: HERO_SEAL_HASH,
    tier: "certified",
    size: 96,
    text: false,
  });
  return (
    <div className={styles.invoiceDoc}>
      <div className={styles.invHead}>
        <div>
          <div className={styles.invTitle}>Invoice INV-2026-042</div>
          <div className={styles.invParties}>Horizon Consulting → Acme Corp</div>
        </div>
        <div className={styles.invDate}>2026-06-01</div>
      </div>

      <div className={styles.invLabel}>Bill To</div>
      <div className={styles.invBillTo}>
        <strong>Acme Corp</strong>
        <span>accounts@acme.com</span>
      </div>

      <div className={styles.invLabel}>Line Items</div>
      <table className={styles.invTable}>
        <thead>
          <tr>
            <th>Description</th>
            <th>Qty</th>
            <th>Unit</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Strategy consulting — May 2026</td>
            <td>40</td>
            <td>150.00</td>
            <td>6,000.00</td>
          </tr>
          <tr>
            <td>Systems integration</td>
            <td>12</td>
            <td>175.00</td>
            <td>2,100.00</td>
          </tr>
          <tr>
            <td>Compliance review</td>
            <td>1</td>
            <td>405.00</td>
            <td>405.00</td>
          </tr>
        </tbody>
      </table>

      <div className={styles.invMetric}>
        <span>Subtotal</span>
        <span>8,505.00 USD</span>
      </div>
      <div className={styles.invMetric}>
        <span>Tax (5%)</span>
        <span>425.25 USD</span>
      </div>
      <div className={styles.invMetricTotal}>
        <span>Total Due</span>
        <span>8,930.25 USD</span>
      </div>

      {/* The trust STAMP — the single mark that certifies the document. */}
      <div className={styles.invStamp}>
        <span
          className={styles.invStampSeal}
          dangerouslySetInnerHTML={{ __html: stamp }}
        />
        <span className={styles.invStampCap}>
          <span>Signed Layla Hassan · Finance Director</span>
          <span>Sealed 1 Jun 2026</span>
          <span className={styles.invStampHash}>19fba2465d…</span>
        </span>
      </div>
    </div>
  );
}

/* ── Page ─────────────────────────────────────────────────────────────── */

export default function Home(): React.ReactElement {
  return (
    <Layout
      title="A plain-text document you can read, query, print, and prove"
      description="IntentText (.it) is an open plain-text format: human-readable documents that are also a queryable database, printable to enterprise PDF, and provable through a three-layer trust model — SHA-256 integrity, Ed25519 signatures, and UTS certification — verifiable by anyone, offline. Arabic-native, agent-ready."
    >
      {/* ── 1 · Hero ─────────────────────────────────────── */}
      <header className={styles.hero}>
        <div className="container">
          <div className={styles.heroGrid}>
            <div className={styles.heroCopy}>
              <div className={styles.heroBadge}>
                <code>.it</code> — IntentText · open format · trust built in
              </div>
              <h1 className={styles.heroTitle}>
                One plain-text file you can <em>read</em>, <em>query</em>,{" "}
                <em>print</em>, and <em>prove</em>.
              </h1>
              <p className={styles.heroSub}>
                IntentText (<code>.it</code>) is an open format for business
                documents — contracts, invoices, tenders, reports. The same
                file is a human-readable document, a queryable database, an
                enterprise PDF, and a <strong>tamper-evident, signable,
                certifiable record</strong> anyone can verify offline. No
                platform, no account, no lock-in.
              </p>
              <div className={styles.installRow}>
                <code className={styles.installCmd}>
                  <span>$</span> npm install -g @dotit/core
                </code>
              </div>
              <div className={styles.heroButtons}>
                <Link
                  className="button button--primary button--lg"
                  to="/docs/guide/quick-start"
                >
                  Get started <ArrowRight size={18} />
                </Link>
                <Link
                  className="button button--secondary button--lg"
                  href="https://editor.uts.qa"
                >
                  Open the editor
                </Link>
                <Link
                  className="button button--secondary button--lg"
                  to="/download"
                >
                  <Monitor size={18} /> Download desktop
                </Link>
                <Link
                  className="button button--link button--lg"
                  to="pathname:///llms.txt"
                >
                  llms.txt for AI agents
                </Link>
              </div>
            </div>
            <div className={styles.heroVisual} aria-hidden="false">
              <div className={styles.heroPaper}>
                <HeroInvoice />
              </div>
              <span className={styles.heroPaperTag}>
                <Lock size={13} /> sealed invoice.it — real renderer output
              </span>
            </div>
          </div>
          <nav className={styles.pillars}>
            <a className={styles.pillar} href="#example">
              <FileText size={22} strokeWidth={1.6} />
              <strong>A document you read</strong>
              <span>Plain text, one intent per line</span>
            </a>
            <a className={styles.pillar} href="#query">
              <Database size={22} strokeWidth={1.6} />
              <strong>A database you query</strong>
              <span>Typed blocks, folder indexes</span>
            </a>
            <a className={styles.pillar} href="#print">
              <Printer size={22} strokeWidth={1.6} />
              <strong>A PDF you ship</strong>
              <span>Themes, page headers, watermarks</span>
            </a>
            <a className={styles.pillar} href="#trust">
              <ShieldCheck size={22} strokeWidth={1.6} />
              <strong>A record you prove</strong>
              <span>Seal · sign · certify · verify</span>
            </a>
          </nav>
        </div>
      </header>

      {/* ── 2 · Live-feel example ────────────────────────── */}
      <section className={styles.section} id="example">
        <div className="container">
          <span className={styles.kicker}>The format</span>
          <h2 className={styles.sectionTitle}>Write this. Ship this.</h2>
          <p className={styles.sectionSub}>
            Every line is one intent: <code>keyword: content | prop: value</code>.
            The source on the left is the single artifact — the invoice on the
            right is <code>dotit invoice.it --html --theme corporate</code>.
          </p>
          <div className={styles.duo}>
            <ItSource title="invoice.it" code={INVOICE_SRC} />
            <InvoicePaper />
          </div>
          <div className={styles.captionRow}>
            <span className={styles.captionChip}>
              Two-sided rows — <code>end:</code>
            </span>
            <span className={styles.captionChip}>
              Inline styled spans — <code>[text]&#123;…&#125;</code>
            </span>
            <span className={styles.captionChip}>
              Running header / footer with page counters
            </span>
            <span className={styles.captionChip}>
              Typed blocks — <code>metric:</code>, <code>deadline:</code>,{" "}
              <code>contact:</code>
            </span>
          </div>
        </div>
      </section>

      {/* ── 3 · Arabic-native ────────────────────────────── */}
      <section className={`${styles.section} ${styles.sectionAlt}`} id="arabic">
        <div className="container">
          <span className={styles.kicker}>عربي أصيل</span>
          <h2 className={styles.sectionTitle}>Arabic is a first language</h2>
          <p className={styles.sectionSub}>
            Not translated — native. Write the keywords themselves in Arabic:{" "}
            <code>عنوان:</code> <code>قسم:</code> <code>جهة:</code>{" "}
            <code>مهلة:</code> <code>توقيع:</code>. The document below is a
            complete, sealable services contract.
          </p>
          <div className={styles.duo} dir="rtl">
            <ItSource title="عقد-الخدمات.it" code={ARABIC_SRC} rtl />
            <ArabicPaper />
          </div>
          <div className={styles.captionRow}>
            <span className={styles.captionChip}>
              28 Arabic keyword aliases — full canonical semantics
            </span>
            <span className={styles.captionChip}>
              RTL automatic — layout mirrors via CSS logical properties
            </span>
            <span className={styles.captionChip}>
              Keywords round-trip as written — sealed Arabic docs keep their
              hash
            </span>
            <span className={styles.captionChip}>
              One query spans languages — <code>--type deadline</code> finds{" "}
              <code>مهلة:</code> too
            </span>
          </div>
        </div>
      </section>

      {/* ── 4 · Enterprise print / PDF ───────────────────── */}
      <section className={styles.section} id="print">
        <div className="container">
          <div className={styles.split}>
            <div className={styles.splitCopy}>
              <span className={styles.kicker}>Print &amp; PDF</span>
              <h2>Enterprise paper, from plain text</h2>
              <p>
                The page is part of the document. Paper size, margins, running
                headers and footers, watermarks, and house typography are all
                declared in the same <code>.it</code> file — no CSS, no Word
                template drift.
              </p>
              <ul className={styles.featureList}>
                <li>
                  <LayoutDashboard size={18} strokeWidth={1.7} />
                  <div>
                    <strong>WYSIWYG editor</strong>
                    <p>
                      Word-like pages at{" "}
                      <Link href="https://editor.uts.qa">editor.uts.qa</Link> —
                      what you see on the canvas is what prints.
                    </p>
                  </div>
                </li>
                <li>
                  <Printer size={18} strokeWidth={1.7} />
                  <div>
                    <strong>@page control with live counters</strong>
                    <p>
                      <code>header:</code> / <code>footer:</code> render in the
                      print margins with <code>&#123;&#123;page&#125;&#125;</code> /{" "}
                      <code>&#123;&#123;pages&#125;&#125;</code> resolved per
                      page. <code>watermark: DRAFT</code> overlays every page.
                    </p>
                  </div>
                </li>
                <li>
                  <FileText size={18} strokeWidth={1.7} />
                  <div>
                    <strong>8 themes, Word-parity typography</strong>
                    <p>
                      corporate, legal, editorial, technical, minimal, warm,
                      dark, print — plus <code>leading:</code>,{" "}
                      <code>space-before:</code>, <code>space-after:</code> per
                      block or document-wide via <code>style:</code> rules.
                    </p>
                  </div>
                </li>
                <li>
                  <Server size={18} strokeWidth={1.7} />
                  <div>
                    <strong>Server-side PDF bytes</strong>
                    <p>
                      Browser printing needs zero dependencies. For invoicing
                      pipelines and archives, <code>@dotit/pdf</code> merges,
                      seals, and returns real PDF bytes in one call.
                    </p>
                  </div>
                </li>
              </ul>
            </div>
            <div className={styles.codeStack}>
              <figure className={styles.shotFig}>
                <div className={styles.shot}>
                  <img
                    src={useBaseUrl("/img/landing-invoice.png")}
                    alt="Invoice rendered by @dotit/core — corporate theme, two-sided title row, line-item table, totals, and payment deadline"
                    width={1440}
                    height={1276}
                    loading="lazy"
                  />
                </div>
                <figcaption className={styles.shotCaption}>
                  Real renderer output — <code>dotit invoice.it --print --theme
                  corporate</code>
                </figcaption>
              </figure>
              <ItSource title="report.it — page setup" code={PRINT_SRC} />
              <DarkCode title="issue-invoice.ts — @dotit/pdf" code={PDF_SRC} />
            </div>
          </div>
        </div>
      </section>

      {/* ── 5 · Trust (flagship) ─────────────────────────── */}
      <section className={`${styles.section} ${styles.sectionAlt}`} id="trust">
        <div className="container">
          <span className={styles.kicker}>Trust</span>
          <h2 className={styles.sectionTitle}>
            Three layers of proof, inside one file
          </h2>
          <p className={styles.sectionSub}>
            A bank, a court, or a procurement office needs to know three things
            about a document: that it hasn&apos;t changed, who stands behind it,
            and that they are a real, vetted entity. IntentText answers all
            three — and anyone can check the answers offline, with no app and no
            account.
          </p>

          <div className={styles.trustLayers}>
            <div className={styles.trustLayer}>
              <div className={styles.trustLayerHead}>
                <Lock size={22} strokeWidth={1.7} />
                <span className={styles.trustLayerNum}>1</span>
                <h3>Integrity</h3>
              </div>
              <p className={styles.trustLayerLead}>
                <em>Has anything changed?</em>
              </p>
              <p>
                <code>seal:</code> freezes the content and stamps it with a
                SHA-256 hash. Change a single character — a date, a number, a
                payment term — and the hash no longer matches. Tampering becomes
                visible instantly, to anyone, forever.
              </p>
              <span className={styles.trustLayerProof}>
                <FileCheck size={14} /> Verify with any SHA-256 — no vendor
              </span>
            </div>

            <div className={styles.trustLayer}>
              <div className={styles.trustLayerHead}>
                <Fingerprint size={22} strokeWidth={1.7} />
                <span className={styles.trustLayerNum}>2</span>
                <h3>Identity</h3>
              </div>
              <p className={styles.trustLayerLead}>
                <em>Who signed it?</em>
              </p>
              <p>
                <code>sign:</code> is a real Ed25519 cryptographic signature, not
                a typed name. It proves the document was signed by the holder of
                a specific private key, and it verifies offline against the
                public key embedded in the file.
              </p>
              <span className={styles.trustLayerProof}>
                <PenLine size={14} /> Ed25519 · <code>@dotit/sign</code>
              </span>
            </div>

            <div className={styles.trustLayer}>
              <div className={styles.trustLayerHead}>
                <BadgeCheck size={22} strokeWidth={1.7} />
                <span className={styles.trustLayerNum}>3</span>
                <h3>Authority</h3>
              </div>
              <p className={styles.trustLayerLead}>
                <em>Is the signer a vetted entity?</em>
              </p>
              <p>
                <code>certify:</code> binds the signature to a KYC-verified legal
                entity through a UTS certification. An offline root key vouches
                for an online issuing key; that chain travels inside the
                document and verifies against the root alone.
              </p>
              <span className={styles.trustLayerProof}>
                <ShieldCheck size={14} /> root → issuing key → document
              </span>
            </div>
          </div>

          <div className={styles.split}>
            <div className={styles.splitCopy}>
              <h2>One artifact, four jobs at once</h2>
              <p>
                That is what makes <code>.it</code> different. The very same
                file you read on screen is the file a system queries, the file
                that prints to PDF, and the tamper-evident record a third party
                verifies — with no conversion, no export step, and no platform
                in the middle.
              </p>
              <ul className={styles.featureList}>
                <li>
                  <FileCheck size={18} strokeWidth={1.7} />
                  <div>
                    <strong>Approvals are sealed with the body</strong>
                    <p>
                      <code>approve:</code> lines are part of what the hash
                      covers. The append-only audit log below the{" "}
                      <code>history:</code> boundary never disturbs the seal.
                    </p>
                  </div>
                </li>
                <li>
                  <GitBranch size={18} strokeWidth={1.7} />
                  <div>
                    <strong>Formal amendments, not silent edits</strong>
                    <p>
                      A sealed document changes only through{" "}
                      <code>amendment:</code> — <code>was:</code> /{" "}
                      <code>now:</code> records the change while the original
                      seal stays intact and provable.
                    </p>
                  </div>
                </li>
                <li>
                  <Clock size={18} strokeWidth={1.7} />
                  <div>
                    <strong>Verifiable in twenty years</strong>
                    <p>
                      No service to call, no key to license. Open format, open
                      math — the proof is in the file and stays there.
                    </p>
                  </div>
                </li>
              </ul>
            </div>
            <div className={styles.codeStack}>
              <TerminalPane
                title="seal · sign · certify · verify — dotit CLI"
                lines={TRUST_TERM}
              />
            </div>
          </div>

          {/* Hash-Based Ambient Seal — the flagship visual */}
          <div className={styles.sealFeature}>
            <div className={styles.sealHead}>
              <span className={styles.kicker}>
                <Stamp
                  size={14}
                  strokeWidth={1.8}
                  style={{ verticalAlign: "-2px", marginInlineEnd: 6 }}
                />
                Hash-Based Ambient Seal
              </span>
              <h3 className={styles.sectionTitle}>Trust you can see</h3>
              <p className={styles.sectionSub}>
                A hash is a string of hex — true, but invisible. The Ambient
                Seal turns that hash into a mark on the page: a pattern drawn
                <em> deterministically</em> from the document&apos;s SHA-256.
                Same document, identical seal — every time. Change one character
                and the seal becomes completely different. Trust stops being
                something you check and becomes something you{" "}
                <em>recognise at a glance</em>.
              </p>
            </div>
            <LiveSealRow />
            <figure className={styles.sealFig}>
              <div className={styles.shot}>
                <img
                  src={useBaseUrl("/img/trust-seal-styles.png")}
                  alt="Ten Hash-Based Ambient Seal styles — line wave, dot field, polygon flow, concentric, organic, ripple, swirl, percolation, geometric weave, fractal edge — each generated deterministically from a document's SHA-256 hash and shown in a document corner"
                  loading="lazy"
                  decoding="async"
                />
              </div>
              <figcaption className={styles.shotCaption}>
                Each seal is generated from the SHA-256 of the document — same
                document, identical seal; any change, a completely different one.
              </figcaption>
            </figure>
            <figure className={styles.sealFig}>
              <div className={styles.shot}>
                <img
                  src={useBaseUrl("/img/trust-seal-placements.png")}
                  alt="Ambient Seal placement system — the seal rendered as a corner mark in the top-right, left margin, right side and bottom corner of a printed document, with mock-ups on real paper"
                  loading="lazy"
                  decoding="async"
                />
              </div>
              <figcaption className={styles.shotCaption}>
                It lives where a wax seal would — a quiet corner mark on the
                printed document, in English or Arabic, light on ink.
              </figcaption>
            </figure>
          </div>
        </div>
      </section>

      {/* ── 5b · Desktop, editor & converters ────────────── */}
      <section className={styles.section} id="apps">
        <div className="container">
          <div className={styles.split}>
            <div className={styles.splitCopy}>
              <span className={styles.kicker}>Apps &amp; converters</span>
              <h2>Edit on the canvas. Open on the desktop.</h2>
              <p>
                You don&apos;t have to write <code>.it</code> by hand. A Word-like
                editor and a native desktop app give business users the
                familiar surface — the trust model rides along underneath.
              </p>
              <ul className={styles.featureList}>
                <li>
                  <LayoutDashboard size={18} strokeWidth={1.7} />
                  <div>
                    <strong>WYSIWYG editor — what you see is what prints</strong>
                    <p>
                      A ribbon, real pages, page sizes from A5 to A1 in portrait
                      or landscape, easy zoom, and a live trust banner. Export to
                      PDF is the on-screen page, byte-for-byte. Open it at{" "}
                      <Link href="https://editor.uts.qa">editor.uts.qa</Link>.
                    </p>
                  </div>
                </li>
                <li>
                  <Monitor size={18} strokeWidth={1.7} />
                  <div>
                    <strong>Desktop app — double-click to open a .it file</strong>
                    <p>
                      A native cross-platform app (macOS, Windows, Linux) built
                      on Tauri. Open, read, and edit <code>.it</code> files from
                      disk, with an always-visible trust badge showing the
                      integrity, signature, and certification status of the
                      document in front of you.
                    </p>
                  </div>
                </li>
                <li>
                  <ArrowLeftRight size={18} strokeWidth={1.7} />
                  <div>
                    <strong>Convert what you already have</strong>
                    <p>
                      <code>dotit convert</code> imports Markdown, HTML,{" "}
                      <strong>Excel (XLSX)</strong> and <strong>Word
                      (DOCX)</strong> — and exports back to XLSX and DOCX. Your
                      spreadsheets and contracts become queryable, sealable{" "}
                      <code>.it</code>, and ship back out unchanged.
                    </p>
                  </div>
                </li>
              </ul>
            </div>
            <div className={styles.codeStack}>
              <div className={styles.appShowcase}>
                <div className={styles.appCard}>
                  <div className={styles.appCardHead}>
                    <LayoutDashboard size={16} strokeWidth={1.8} /> Editor ·
                    editor.uts.qa
                  </div>
                  <div className={styles.appChips}>
                    <span className={styles.appChip}>Ribbon toolbar</span>
                    <span className={styles.appChip}>A5–A1 · portrait/landscape</span>
                    <span className={styles.appChip}>Zoom 25–300%</span>
                    <span className={styles.appChip}>Trust banner</span>
                    <span className={styles.appChip}>WYSIWYG PDF</span>
                  </div>
                </div>
                <div className={styles.appCard}>
                  <div className={styles.appCardHead}>
                    <Monitor size={16} strokeWidth={1.8} /> Desktop · macOS ·
                    Windows · Linux
                  </div>
                  <div className={styles.appChips}>
                    <span className={styles.appChip}>Double-click open</span>
                    <span className={styles.appChip}>Edit &amp; autosave</span>
                    <span className={styles.appChip}>Live trust badge</span>
                    <span className={styles.appChip}>Folder vaults</span>
                    <span className={styles.appChip}>Tauri-native</span>
                  </div>
                </div>
              </div>
              <div className={styles.convertFlow}>
                <span className={styles.convertFmt}>
                  <FileText size={13} /> .md
                </span>
                <span className={styles.convertFmt}>
                  <Globe size={13} /> .html
                </span>
                <span className={styles.convertFmt}>
                  <FileSpreadsheet size={13} /> .xlsx
                </span>
                <span className={styles.convertFmt}>
                  <FileText size={13} /> .docx
                </span>
                <ArrowLeftRight size={15} className={styles.convertArrow} />
                <span className={`${styles.convertFmt} ${styles.convertIt}`}>
                  <FileCheck size={13} /> .it
                </span>
              </div>
              <TerminalPane title="convert — dotit CLI" lines={CONVERT_TERM} />
            </div>
          </div>
        </div>
      </section>

      {/* ── 6 · A folder is a database ───────────────────── */}
      <section className={`${styles.section} ${styles.sectionAlt}`} id="query">
        <div className="container">
          <div className={styles.split}>
            <div className={styles.splitCopy}>
              <span className={styles.kicker}>Query</span>
              <h2>A folder of documents is a database</h2>
              <p>
                Every block is typed and every property is queryable — so a
                directory of contracts answers questions without a database,
                an importer, or a server.
              </p>
              <ul className={styles.featureList}>
                <li>
                  <Search size={18} strokeWidth={1.7} />
                  <div>
                    <strong>Query files, folders, or globs</strong>
                    <p>
                      Filter by type, author, status, section, or content;
                      output as table, JSON, or CSV. Date ranges work because
                      dates are ISO 8601.
                    </p>
                  </div>
                </li>
                <li>
                  <Database size={18} strokeWidth={1.7} />
                  <div>
                    <strong>Self-healing indexes</strong>
                    <p>
                      Each folder owns a shallow <code>.it-index</code> that
                      refreshes lazily on query. The <code>.it</code> files
                      stay the source of truth — greppable and git-diffable.
                    </p>
                  </div>
                </li>
                <li>
                  <Code2 size={18} strokeWidth={1.7} />
                  <div>
                    <strong>Same engine in code</strong>
                    <p>
                      <code>
                        queryBlocks(doc, "type:task owner:Ahmed sort:due:asc
                        limit:5")
                      </code>{" "}
                      — one function, no schema migration, works offline.
                    </p>
                  </div>
                </li>
              </ul>
            </div>
            <TerminalPane title="query — dotit CLI" lines={QUERY_TERM} />
          </div>
        </div>
      </section>

      {/* ── 7 · For AI agents ────────────────────────────── */}
      <section className={styles.section} id="agents">
        <div className="container">
          <span className={styles.kicker}>For AI agents</span>
          <h2 className={styles.sectionTitle}>
            Agents learn the format from one URL
          </h2>
          <p className={styles.sectionSub}>
            IntentText is designed to be authored by models as much as by
            people — deterministic grammar, no layout ambiguity, and trust
            operations an agent can run.
          </p>
          <div className={styles.cardGrid}>
            <div className={styles.card}>
              <h3>
                <Globe size={20} strokeWidth={1.7} /> /llms.txt — the whole
                format, one request
              </h3>
              <div className={styles.llmsUrl}>dotit.uts.qa/llms.txt</div>
              <p>
                The complete machine reference: line grammar, all 38 canonical
                keywords, styling layers, templates and merge, the trust
                model, and generation rules. Point any LLM at it and it writes
                valid <code>.it</code> — documents, templates, and workflows —
                immediately.
              </p>
              <div className={styles.cardFooter}>
                <Link
                  className="button button--primary"
                  to="pathname:///llms.txt"
                >
                  Open /llms.txt <ArrowRight size={16} />
                </Link>
              </div>
            </div>
            <div className={styles.card}>
              <h3>
                <Bot size={20} strokeWidth={1.7} /> @dotit/mcp — 17 tools, any
                agent
              </h3>
              <div className={styles.toolChips}>
                {MCP_TOOLS.map((t) => (
                  <span key={t} className={styles.toolChip}>
                    {t}
                  </span>
                ))}
              </div>
              <DarkCode title="mcp.json" code={MCP_SRC} />
            </div>
          </div>
          <p className={styles.agentKeywords}>
            And agents don&apos;t just read <code>.it</code> — they run on it:{" "}
            <code>step:</code>, <code>decision:</code>, <code>gate:</code>,{" "}
            <code>trigger:</code>, <code>result:</code>, <code>policy:</code>,{" "}
            <code>audit:</code> define executable workflows with human
            checkpoints.{" "}
            <Link to="/docs/guide/for-agents">Read the agent guide →</Link>
          </p>
        </div>
      </section>

      {/* ── 8 · Ecosystem ────────────────────────────────── */}
      <section className={`${styles.section} ${styles.sectionAlt}`} id="ecosystem">
        <div className="container">
          <span className={styles.kicker}>Ecosystem</span>
          <h2 className={styles.sectionTitle}>Everything ships under @dotit</h2>
          <p className={styles.sectionSub}>
            A zero-dependency core, opt-in companions, and tooling for every
            surface you work on.
          </p>
          <div className={styles.ecoGrid}>
            <Link
              className={styles.ecoCard}
              href="https://npmjs.com/package/@dotit/core"
            >
              <Package size={20} strokeWidth={1.7} />
              <strong>@dotit/core</strong>
              <span>
                Parser, HTML/print renderer, query, trust, templates — and the{" "}
                <code>dotit</code> CLI. Zero dependencies.
              </span>
            </Link>
            <Link
              className={styles.ecoCard}
              href="https://npmjs.com/package/@dotit/pdf"
            >
              <Printer size={20} strokeWidth={1.7} />
              <strong>@dotit/pdf</strong>
              <span>
                Server-side PDF bytes: merge → seal → render in one{" "}
                <code>issuePDF()</code> call.
              </span>
            </Link>
            <Link
              className={styles.ecoCard}
              href="https://npmjs.com/package/@dotit/sign"
            >
              <Fingerprint size={20} strokeWidth={1.7} />
              <strong>@dotit/sign</strong>
              <span>
                Ed25519 signatures and UTS certification — identity and
                authority on top of the seal.
              </span>
            </Link>
            <Link
              className={styles.ecoCard}
              href="https://npmjs.com/package/@dotit/mcp"
            >
              <Server size={20} strokeWidth={1.7} />
              <strong>@dotit/mcp</strong>
              <span>
                MCP server with 17 tools — parse, render, query, seal, sign,
                certify, verify from any AI agent.
              </span>
            </Link>
            <Link className={styles.ecoCard} href="https://editor.uts.qa">
              <Monitor size={20} strokeWidth={1.7} />
              <strong>Desktop app</strong>
              <span>
                Native Tauri app for macOS, Windows and Linux — double-click a{" "}
                <code>.it</code> file, edit, and watch the trust badge.
              </span>
            </Link>
            <Link
              className={styles.ecoCard}
              href="https://github.com/intenttext/IntentText/tree/main/packages/vscode"
            >
              <Code2 size={20} strokeWidth={1.7} />
              <strong>VS Code extension</strong>
              <span>
                Syntax highlighting from the same keyword registry the parser
                uses.
              </span>
            </Link>
            <Link className={styles.ecoCard} href="https://editor.uts.qa">
              <LayoutDashboard size={20} strokeWidth={1.7} />
              <strong>Editor</strong>
              <span>
                Word-like WYSIWYG pages, template mode, trust chips, print
                preview — in the browser.
              </span>
            </Link>
            <Link
              className={styles.ecoCard}
              href="https://github.com/intenttext/IntentText"
            >
              <GitBranch size={20} strokeWidth={1.7} />
              <strong>GitHub</strong>
              <span>
                The spec, the source, the issues. The format is open — the
                file is yours.
              </span>
            </Link>
          </div>
        </div>
      </section>

      {/* ── CTA ──────────────────────────────────────────── */}
      <section className={styles.cta}>
        <div className="container">
          <h2>One file. The whole document lifecycle.</h2>
          <p className={styles.sectionSub}>
            Author → merge → print → sign → seal → query → verify. Open
            format, no lock-in.
          </p>
          <div className={styles.installRow}>
            <code className={styles.installCmd}>
              <span>$</span> npm install -g @dotit/core
            </code>
          </div>
          <div className={styles.heroButtons}>
            <Link
              className="button button--primary button--lg"
              to="/docs/guide/quick-start"
            >
              Get started <ArrowRight size={18} />
            </Link>
            <Link
              className="button button--secondary button--lg"
              to="/docs/guide/concepts"
            >
              Read the docs
            </Link>
          </div>
        </div>
      </section>
    </Layout>
  );
}
